name: Make Docs
on:
  push:
    branches: ["master", "dev", "reuse_ci"]
    paths:
      - '.github/workflows/make_docs.yml'
      - 'src/**'
      - 'docs/**'
    tags: '*'
  pull_request:
    branches: ["master", "dev"]
    paths:
      - '.github/workflows/make_docs.yml'
      - 'src/**'
      - 'docs/**'
  workflow_dispatch:
    
jobs:
  make_docs:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/make_docs.yml@master